version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    # environment:
    #   KAFKA_ADVERTISED_HOST_NAME: localhost
    #   KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    #   KAFKA_BROKER_ID: 1
    #   # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    #   # KAFKA_CREATE_TOPICS: "stream-in:1:1,stream-out:1:1"
    # depends_on:
    #   - zookeeper
    # container_name: kafka